apiVersion: v1
kind: Service
metadata:
  name: maple-project-postgres-service
  namespace: maple-system
spec:
  type: ClusterIP
  ports:
    - port: 5403
      targetPort: 5432
  selector:
    app: maple-project-postgres
